include:
  - board: nice_nano_v2
    shield: littlefoot 
    artifact-name: littlefoot
  - board: nice_nano_v2
    shield: littlefoot_24
    artifact-name: littlefoot_24
  - board: seeeduino_xiao_ble
    shield: littlefoot_24_dongle dongle_display
    artifact-name: littlefoot_24_dongle
  - board: nice_nano_v2
    shield: settings_reset
  - board: seeeduino_xiao_ble
    shield: settings_reset